config/routes.rb
Rails.application.routes.draw do
  resources :postmods
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :refunds
  root to: 'pages#home'
  devise_for :users

  get '/pages', to: 'pages#about', as: 'pages' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/postmod.rb
class Postmod < ApplicationRecord
  belongs_to :user
  has_attached_file :pdfile
  #attr_accessible :pdfile
  validates_attachment_content_type :pdfile, content_type: ['application/pdf'], :allow_nil => true
  


  
  validates  :approved, :presence => true, :if => :amendfeerec?
  validates  :approved, :presence => true, :if => :amendfeerecgm?

  validates  :approved, :presence => true, :if => :ammendcost?

  validates  :adminreason, :presence => true, :if => :denied?  
  validates  :adminreason, :presence => true, :if => :addinfo?  

  validates :reason, :presence => true, :if => :transletter?
  validates :reason, :presence => true, :if => :invoice?
  validates :reason, :presence => true, :if => :vvslip?
  validates :reason, :presence => true, :if => :sscertificate?
  #validates :reason, :presence => true, :if => :otherasdbox?
  validates :reason, :presence => true, :if => :popayment?
  validates :reason, :presence => true, :if => :certorigin?
  validates :reason, :presence => true, :if => :worksheet?
  validates :reason, :presence => true, :if => :overlandedcert?
  validates :entrynum, :presence => true
  validates :officecode, :presence => true

end

app/controllers/postmods_controller.rb
class PostmodsController < ApplicationController
  before_action :set_postmod, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #, except: [:show, :index]
  # GET /postmods
  # GET /postmods.json
  def index
    @postmods = Postmod.all
  end

  # GET /postmods/1
  # GET /postmods/1.json
  def show
  end

  # GET /postmods/new
  def new
    @postmod = Postmod.new
  end

  # GET /postmods/1/edit
  def edit
  end

  # POST /postmods
  # POST /postmods.json
  def create
    @postmod = Postmod.new(postmod_params)
    @postmod.user = current_user
    @postmod.otherasdbox = @current_user.email
    respond_to do |format|
      if @postmod.save
       ######### PostmodMailer.with(postmod: @postmod).welcome_email.deliver_later
         PostmodMailer.welcome_email(@postmod).deliver
        #redirect_back(fallback_location: root_path)
     
        format.html { redirect_to @postmod, notice: 'Post Modification Request has been submitted.' }
     ####### #  @postmod.save_attachments(postmod_params) if params[:postmod][:postmod_data]
       # format.html { redirect_to @postmod, notice: 'File successfully uploaded.' }
        
        #format.json { render :show, status: :created, location: @postmod }       
      else
        format.html { render :new }
        format.json { render json: @postmod.errors, status: :unprocessable_entity }

         flash[:error] = @postmod.errors.full_messages
      #redirect_back(fallback_location: root_path)
      end
      
    end
  end


  # PATCH/PUT /postmods/1
  # PATCH/PUT /postmods/1.json
  def update
    respond_to do |format|
      if @postmod.update(postmod_params)
        PostmodMailer.welcome_email(@postmod).deliver
        format.html { redirect_to @postmod, notice: 'Postmod was successfully updated.' }
        format.json { render :show, status: :ok, location: @postmod }
      else
        format.html { render :edit }
        format.json { render json: @postmod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postmods/1
  # DELETE /postmods/1.json
  def destroy
    @postmod.destroy
    respond_to do |format|
      format.html { redirect_to postmods_url, notice: 'Postmod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postmod
      @postmod = Postmod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def postmod_params
      params.require(:postmod).permit(:officecode, :entrynum, :created_at, :updated_at, :mof, :beltrade, :motourism, :mohealth, :moeducation, :mosecurity, :dciagency, :bosie, :other, :government, :nagreement, :doe, :cpharmacy, :townership, :centralbank, :exporter, :importer, :noitems, :nopackage, :vessel, :fccontainernum, :location, :nmass, :tainvoice, :description, :commcode, :vinserial, :airbill, :origin, :gmass, :currency, :iquantity, :procexproccode, :itemvalue, :prevdocrefnum, :bolading, :amendfeerec, :amendfeerecgm, :transletter, :invoice, :vvslip, :sscertificate, :otherasd, :popayment, :certorigin, :worksheet, :overlandedcert, :othercertbox, :otherasdbox, :reason, :approved, :denied, :pdfile, :addinfo, :otherexcert, :adminreason, :ammendcost, :recorded, :brokeremail)
    end
end

app/helpers/postmods_helper.rb
module PostmodsHelper
end

app/views/postmods/edit.html.erb
<h1>Editing Postmod</h1>

<%= render 'form', postmod: @postmod %>

<%= link_to 'Show', @postmod %> |
<%= link_to 'Back', postmods_path %>

app/views/postmods/index.html.erb
<html>
<head>
<title> Customs Application For Post Modification</title>
<style>
table, th, td, tr {
 border: 1px solid black;
 border-collapse: collapse;
 text-align: center;
 background-color:#f5f3f2;
}
</style>



        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
 

</head>
<body class="container">

<p id="notice"><%= notice %></p>

<h1 align="center">Submitted Applications For Post Modification</h1>
<br><br>
<%= link_to 'Home', root_path %>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<br><br>
<a href="http://customsapplications.herokuapp.com/admin">Administration Panel</a><br><br>
<%= link_to 'View List of Applications Submitted for Refund of Duty', refunds_path %><br><br>
<%= link_to 'New Application for Refund of Duty', new_refund_path %><br><br>
<%= link_to 'View List of Applications Submitted for Post Modification', postmods_path %><br><br>
<%= link_to 'New Application for Post Modification', new_postmod_path %>
<br><br>


<p id="notice"><%= notice %></p>

<h2 align="center">Requests For Post Modification</h2>


<table width="100%">
  <thead>
    <tr>
      <th>Request ID</th>
      <th>Entry Number</th>
      <th>Office Code</th>
      <th>Username</th>
      <th>Date/Time Created</th> 
      <th>Date/Time Updated</th>  
    </tr>
  </thead>
<tbody>
    <% @postmods.each do |postmod| %>
    <% if postmod.user.username == current_user.username || current_user.admin == true %>
      <tr>
        <td><%= postmod.id %></td>
        <td><%= postmod.entrynum %></td>
        <td><%= postmod.officecode%></td>
        <td><%= postmod.user.username %></td>
         <td><%= postmod.created_at %></td>
         <td><%= postmod.updated_at %></td>
      
        <td><%=link_to 'Show', postmod %></td> 
        <% if current_user.admin == true %>
        <td><%= link_to 'Edit', edit_postmod_path(postmod) %></td>
        <% end %>
        <% if current_user.admin == true %>
        <td><%= link_to 'Destroy', postmod, method: :delete, data: {confirm: 'Are You Sure?' } %>
        <% end %>
       </td>
      </tr>
    <% end %>

<%end%>
</tbody>
</table>
</body></html>

app/views/postmods/new.html.erb
<h1 align="center">New Post Modification Request Form</h1><br>

<%= render 'form', postmod: @postmod %>

<%= link_to 'Back', postmods_path %>