config/routes.rb
Rails.application.routes.draw do
  resources :postmods
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :refunds
  root to: 'pages#home'
  devise_for :users

  get '/pages', to: 'pages#about', as: 'pages' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/refund.rb
class Refund < ApplicationRecord
  belongs_to :user

  attr_readonly :vessel, :rotNum, :entryNum, :refundof, :enteredAs, :enteredAsQ, :enteredAsV, :enteredAsR, :enteredAsD, :shouldBe, :shouldBeQ, :shouldBeV, :shouldBeR, :shouldBeD, :reasonSupportRefund, :refundClaimed, :date, :signature




end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  before_action :set_refund, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /refunds
  # GET /refunds.json
  def index
    @refunds = Refund.all
  end

  # GET /refunds/1
  # GET /refunds/1.json
  def show
  end

  # GET /refunds/new
  def new
    @refund = Refund.new
  end

  # GET /refunds/1/edit
  def edit
  end

  # POST /refunds
  # POST /refunds.json
  def create
    @refund = Refund.new(refund_params)
    @refund.user = current_user
    respond_to do |format|
      if @refund.save
        format.html { redirect_to @refund, notice: 'Refund was successfully created.' }
        format.json { render :show, status: :created, location: @refund }
      else
        format.html { render :new }
        format.json { render json: @refund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refunds/1
  # PATCH/PUT /refunds/1.json
  def update
    respond_to do |format|
      if @refund.update(refund_params)
        format.html { redirect_to @refund, notice: 'Refund was successfully updated.' }
        format.json { render :show, status: :ok, location: @refund }
      else
        format.html { render :edit }
        format.json { render json: @refund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refunds/1
  # DELETE /refunds/1.json
  def destroy
    @refund.destroy
    respond_to do |format|
      format.html { redirect_to refunds_url, notice: 'Refund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refund
      @refund = Refund.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def refund_params
      params.require(:refund).permit(:vessel, :rotNum, :entryNum, :refundof, :enteredAs, :enteredAsQ, :enteredAsV, :enteredAsR, :enteredAsD, :shouldBe, :shouldBeQ, :shouldBeV, :shouldBeR, :shouldBeD, :reasonSupportRefund, :refundClaimed, :date, :signature, :appDate, :compSig, :claimNum, :receivedDate, :claimantSig)
    end
end

app/helpers/refunds_helper.rb
module RefundsHelper
end

app/views/refunds/_form.html.erb
<html>
<head>
<title> Customs Application For Refund Of Duty </title>
<style>
table, th, td, tr {
 border: 1px solid black;
 border-collapse: collapse;
 text-align: center;
 background-color:#f5f3f2;
}

label{
display: block
}
</style>


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  

</head> 
<body class="container">

<%= link_to 'Home', root_path %>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<br><br>

<%= link_to 'View List of Applications Submitted for Refund of Duty', refunds_path %><br><br>
<br><br>


<%= form_with(model: refund, local: true) do |form| %>
  <% if refund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(refund.errors.count, "error") %> prohibited this refund from being saved:</h2>

      <ul>
        <% refund.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Vessel_Name %>
    <%= form.text_field :vessel %>
    <%= form.label :Rotation_Number %>
    <%= form.number_field :rotNum %>
    <%= form.label :Entry_Number %>
    <%= form.number_field :entryNum %>  
</div>
<br>
  <div class="field">
    <p> Application is hereby made for a 
    <%= form.label :refundOf %>
    <%= form.text_field :refundof %> (1)
    in respect of the undermentioned goods imported/exported on the above mentioned entry.
    </p>
  </div>
<table width="100%"><tr><th>Description of Goods</th><th>Quantity (2)</th><th>Value</th><th>Rate</th><th>Duty</th> </tr>
          
<tr align="center">

<td>
  <div class="field">
    <%= form.label :Entered_As %>
    <%= form.text_field :enteredAs %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :Entered_As_Quantity %>
    <%= form.number_field :enteredAsQ %>
  </div> 
</td>

<td>
  <div class="field">
   <%= form.label :Entred_As_Value %>
   <%= form.text_field :entredAsV %>
 </div>
</td>

<td>
  <div class="field">
    <%= form.label :Entered_As_Rate %> 
    <%= form.text_field :enteredAsR %>
  </div>
</td>

<td>
   <div class="field">
     <%= form.label :Entered_As_Duty %>
     <%= form.text_field :enteredAsD %>
   </div>
</td>

</tr>

<tr align="center">

<td>
  <div class="field">
    <%= form.label :should_Be %>
   <%= form.text_field :shouldBe %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Quantity %>
    <%= form.number_field :shouldBeQ %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Value %>
    <%= form.text_field :shouldBeV %>
  </div>
</td>

<td>
 <div class="field">
   <%= form.label :should_Be_Rate %>
    <%= form.text_field :shouldBeR %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Duty %>
    <%= form.text_field :shouldBeD %>
  </div>
</td>

</tr>
</table>
<br>
<hr>
 <br>

<div style="float:left">
(3)
</div>

<div style="float:center">
  <div class="field">
    <%= form.label :reason_In_Support_of_Refund, class: "hidden" %>
    <%= form.text_field :reasonSupportRefund %>
  </div>
</div>
<br>


  <div class="field">
    <%= form.label :Amount_of_refund_Claimed %>
    <%= form.text_field :refundClaimed %>
  </div>
<br>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, value:refund.created_at, :readonly => true %>
  </div>
<br>
  <div class="field">
    <%= form.label :signature %>
    <%= form.text_field :signature, value:current_user.email, :readonly => true  %>
  </div>
<br>
<hr>
<br>

<% if current_user.admin == true %>
<h2 align="center"> FOR OFFICIAL USE ONLY </h2>
<table width="100%">
<tr>
<td valign="top" width="50%">
<p>II</p>
<p>Certified refund correct and payment in order </p><br>
<table width="100%"><thead><th>$</th><th>cts.</th><th>Head</th><th>Subhead</th></thead>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
</table>
</td>

<td valign="top">
<p>III</p>
<p> Payment Approved </p>
  <div class="field">
    <%= form.label :approved_Date %>
    <%= form.date_select :appDate %>
  </div>
<br>
  <div class="field">
    <%= form.label :comptroller_Signature %>
    <%= form.text_field :compSig %>
  </div>
<br>
  <div class="field">
    <%= form.label :claim_Number %>
    <%= form.number_field :claimNum %>
  </div>
</td>
</tr>
</table>

<br><br>
  <div class="field">
    <%= form.label :Received_Date %>
    <%= form.date_select :receivedDate %>
  </div>
<br>
  <div class="field">
    <%= form.label :claimant_Signature %>
    <%= form.text_field :claimantSig %>
  </div>
<% end %>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<br>
<% end %>

<hr>
<br>
<p> This form is to be usd for refund duty, entry tax and export duty only and 2 copies must be lodged for retention.
<br>
<i>Notes</i>
<ol>
<li>Insert here description of refund claimed e.g. entry tax, export tax or duty.</li>
<li> To be completed when refind is occasioned by shortage </li>
<li> Full acurate details to be supplied, e.g. pillage, ullage, damage, etc.</li>
</ol>
<br>
7838-K41-2M
</p>
</body>
</html>

app/views/refunds/edit.html.erb
<h1>Editing Refund</h1>

<%= render 'form', refund: @refund %>

<%= link_to 'Show', @refund %> |
<%= link_to 'Back', refunds_path %>

app/views/refunds/index.html.erb
<html>
<head>
<title> Customs Application For Refund Of Duty </title>
<style>
table, th, td, tr {
 border: 1px solid black;
 border-collapse: collapse;
 text-align: center;
 background-color:#f5f3f2;
}
</style>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>



</head>
<body class="container">

<p id="notice"><%= notice %></p>

<h1 align="center">Submitted Applications For Refund OF Duty</h1>
<br><br>
<%= link_to 'Home', root_path %>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<br><br>
<a href="http://customsapplications.herokuapp.com/admin">Administration Panel</a><br><br>
<%= link_to 'View List of Applications Submitted for Refund of Duty', refunds_path %><br><br>
<%= link_to 'New Application for Refund of Duty', new_refund_path %>
<br><br>

<table width="100%">
  <thead>
    <tr>
      <th>Vessel Name</th>
      <th>Rotion Number</th>
      <th>Entry Number</th>
      <th>Refund Amount</th>
      <th>Application Date</th>
      <th>Signature of Claimant</th>
      
    </tr>
  </thead>
<tbody>
    <% @refunds.each do |refund| %>
    <% if refund.user.username == current_user.username || current_user.admin == true %>
      <tr>
        <td><%= refund.vessel %></td>
        <td><%= refund.rotNum %></td>
        <td><%= refund.entryNum %></td>
        <td><%= refund.refundof %></td>
         <td><%= refund.date %></td>
        <td><%= refund.user.username %></td>
        <td><%=link_to 'Show', refund %>
        <% if current_user.admin == true %>
        <td><%= link_to 'Edit', edit_refund_path(refund) %></td>
        <% end %>
        <% if current_user.admin == true %>
        <td><%= link_to 'Destroy', refund, method: :delete, data: {confirm: 'Are You Sure?' } %>
        <% end %>
       </td>
      </tr>
    <% end %>

<%end%>
</tbody>
</table>

</body>
</html>

app/views/refunds/new.html.erb
<h1 align="center">Customs Application For Refund Of Duty</h1>

<%= render 'form', refund: @refund %>

<%= link_to 'Back', refunds_path %>

app/views/refunds/show.html.erb
<html>
<head>
<title> Customs Application For Refund Of Duty </title>
<style>
table, th, td, tr {
 border: 1px solid black;
 border-collapse: collapse;
 text-align: center;
 background-color:#f5f3f2;
}

label{
display: block
}
</style>
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


</head> 

<body style="background-color:#f5f3f2; " class="container">
<h1 align="center">Customs Application For Refund Of Duty</h1>
<%= link_to 'Home', root_path %>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<br><br>
<a href="http://customsapplications.herokuapp.com/admin">Administration Panel</a><br><br>
<%= link_to 'View List of Applications Submitted for Refund of Duty', refunds_path %><br><br>
<%= link_to 'Application for Refund of Duty', new_refund_path %>
<br>
<br>
<%= form_with(model: @refund, local: true) do |form| %>
  <% if @refund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(refund.errors.count, "error") %> prohibited this refund from being saved:</h2>

      <ul>
        <% @refund.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Vessel_Name %>
    <%= form.text_field :vessel %>
    <%= form.label :Rotation_Number %>
    <%= form.number_field :rotNum %>
    <%= form.label :Entry_Number %>
    <%= form.number_field :entryNum %>  
</div>
<br>
  <div class="field">
    <p> Application is hereby made for a 
    <%= form.label :refundOf %>
    <%= form.text_field :refundof, value:@refund.refundof %> (1)
    in respect of the undermentioned goods imported/exported on the above mentioned entry.
    </p>
  </div>
<table width="100%"><tr><th>Description of Goods</th><th>Quantity (2)</th><th>Value</th><th>Rate</th><th>Duty</th> </tr>
          
<tr align="center">

<td>
  <div class="field">
    <%= form.label :Entered_As %>
    <%= form.text_field :enteredAs, value:@refund.enteredAs %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :Entered_As_Quantity %>
    <%= form.number_field :enteredAsQ, value:@refund.enteredAsQ %>
  </div> 
</td>

<td>
  <div class="field">
   <%= form.label :Entred_As_Value %>
   <%= form.text_field :enteredAsV, value:@refund.enteredAsV %>
 </div>
</td>

<td>
  <div class="field">
    <%= form.label :Entered_As_Rate %> 
    <%= form.text_field :enteredAsR, value:@refund.enteredAsR %>
  </div>
</td>

<td>
   <div class="field">
     <%= form.label :Entered_As_Duty %>
     <%= form.text_field :enteredAsD, value:@refund.enteredAsD %>
   </div>
</td>

</tr>

<tr align="center">

<td>
  <div class="field">
    <%= form.label :should_Be %>
   <%= form.text_field :shouldBe, value:@refund.shouldBe %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Quantity %>
    <%= form.number_field :shouldBeQ, value:@refund.shouldBeQ %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Value %>
    <%= form.text_field :shouldBeV, value:@refund.shouldBeV %>
  </div>
</td>

<td>
 <div class="field">
   <%= form.label :should_Be_Rate %>
    <%= form.text_field :shouldBeR, value:@refund.shouldBeR %>
  </div>
</td>

<td>
  <div class="field">
    <%= form.label :should_Be_Duty %>
    <%= form.text_field :shouldBeD, value:@refund.shouldBeD %>
  </div>
</td>

</tr>
</table>
<br>
<hr>
 <br>

<div style="float:left">
(3)
</div>

<div style="float:center">
  <div class="field">
    <%= form.label :reason_In_Support_of_Refund, class: "hidden" %>
    <%= form.text_field :reasonSupportRefund, value:@refund.reasonSupportRefund %>
  </div>
</div>
<br>


  <div class="field">
    <%= form.label :Amount_of_refund_Claimed %>
    <%= form.text_field :refundClaimed, value:@refund.refundClaimed %>
  </div>
<br>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, value:@refund.date, :readonly=>true %>
  </div>
<br>
  <div class="field">
    <%= form.label :signature %>
    <%= form.text_field :signature, value:@refund.user.email, :readonly=>true %>
  </div>
<br>
<hr>
<br>
<h2 align="center"> FOR OFFICIAL USE ONLY </h2>
<table width="100%">
<tr>
<td valign="top" width="50%">
<p>II</p>
<p>Certified refund correct and payment in order </p><br>
<table width="100%"><thead><th>$</th><th>cts.</th><th>Head</th><th>Subhead</th></thead>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
<tbody><td>place holder</td><td>place holder</td><td>placeholder</td><td>placeholder</td></tbody>
</table>
</td>

<td valign="top">
<p>III</p>
<p> Payment Approved </p>
  <div class="field">
    <%= form.label :approved_Date %>
    <%= form.date_select :appdate, value:@refund.appDate  %>
  </div>
<br>
  <div class="field">
    <%= form.label :comptroller_Signature %>
    <%= form.text_field :compSig, value:@refund.compSig %>
  </div>
<br>
  <div class="field">
    <%= form.label :claim_Number %>
    <%= form.number_field :claimNum, value:@refund.claimNum %>
  </div>
</td>
</tr>
</table>

<br><br>
  <div class="field">
    <%= form.label :receivedDate %>
    <%= form.date_select :receivedDate, value:@refund.receivedDate %>
  </div>
<br>
  <div class="field">
    <%= form.label :claimant_Signature %>
    <%= form.text_field :claimSig, value:@refund.claimantSig %>
  </div>
<br>
<% if current_user.admin == true %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>
<% end %>

<hr>
<br>
<p> This form is to be usd for refund duty, entry tax and export duty only and 2 copies must be lodged for retention.
<br>
<i>Notes</i>
<ol>
<li>Insert here description of refund claimed e.g. entry tax, export tax or duty.</li>
<li> To be completed when refind is occasioned by shortage </li>
<li> Full acurate details to be supplied, e.g. pillage, ullage, damage, etc.</li>
</ol>
<br>
7838-K41-2M
</p>
</body>
</html>